% -------------------------------------------------------------------
%  Generated by MATLAB on 12-Feb-2026 14:58:15
%  MATLAB version: 23.2.0.2365128 (R2023b)
% -------------------------------------------------------------------
saveVarsMat = load('xi.mat');

Actual_Position = saveVarsMat.Actual_Position; % <1x1 struct> too many elements at Actual_Position.time

clear saveVarsMat;
